const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const { detectPaths } = require('./detector');
const { patchIde } = require('./patcher-ide');
const { patchStandalone } = require('./patcher-standalone');
const { clearV8Cache } = require('./cache');

const TASK_NAME = 'AntigravityScrollUnpinWatcher';
const os = require('os');
const LOG_FILE = path.join(os.homedir(), '.antigravity-scroll-unpin.log');

function logEvent(msg) {
  const line = `[${new Date().toISOString()}] ${msg}\n`;
  try {
    fs.appendFileSync(LOG_FILE, line, 'utf8');
  } catch (_) {}
  console.log(msg);
}

/**
 * Starts continuous monitoring of Antigravity installation directories.
 * Automatically re-applies patches whenever Google Antigravity updates.
 */
function startWatcher() {
  const paths = detectPaths();
  logEvent('=== Antigravity Scroll Unpin - Self-Healing Watcher Started ===');

  if (!paths.standalone && !paths.ide) {
    logEvent('✗ No Antigravity installations detected to monitor.');
    process.exit(1);
  }

  logEvent('Monitoring target directories for updates:');
  if (paths.standalone) {
    logEvent(`  [Standalone] ${path.join(paths.standalone, 'resources')}`);
  }
  if (paths.ide) {
    logEvent(`  [IDE]        ${path.join(paths.ide, 'resources', 'app')}`);
  }

  let isSelfHealing = false;
  let debounceTimer = null;
  const triggerSelfHeal = (source) => {
    if (isSelfHealing) return;
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      if (isSelfHealing) return;
      isSelfHealing = true;
      logEvent(`⚡ Update detected from [${source}] - Re-verifying and self-healing...`);
      try {
        if (paths.standalone) {
          const res = patchStandalone(paths.standalone);
          res.actions.forEach(a => logEvent(`   ✓ ${a}`));
          res.errors.forEach(e => logEvent(`   ✗ ${e}`));
        }
        if (paths.ide) {
          const res = patchIde(paths.ide);
          res.actions.forEach(a => logEvent(`   ✓ ${a}`));
          res.errors.forEach(e => logEvent(`   ✗ ${e}`));
        }
        if (paths.ideAppData) {
          clearV8Cache(paths.ideAppData);
        }
        logEvent('✨ Self-heal completed successfully. Antigravity is protected!');
      } catch (err) {
        logEvent(`✗ Error during self-healing: ${err.message}`);
      } finally {
        setTimeout(() => {
          isSelfHealing = false;
        }, 3000);
      }
    }, 2000);
  };

  // Initial check & heal on start
  triggerSelfHeal('Initial Startup');

  // Watch Standalone
  if (paths.standalone) {
    const standaloneRes = path.join(paths.standalone, 'resources');
    if (fs.existsSync(standaloneRes)) {
      try {
        fs.watch(standaloneRes, { recursive: false }, (eventType, filename) => {
          if (filename && filename.toLowerCase().includes('app.asar') && !filename.includes('.bak')) {
            triggerSelfHeal('Standalone app.asar modified');
          }
        });
      } catch (err) {
        console.warn('   ⚠ Could not attach watcher to Standalone resources:', err.message);
      }
    }
  }

  // Watch IDE
  if (paths.ide) {
    const ideApp = path.join(paths.ide, 'resources', 'app');
    if (fs.existsSync(ideApp)) {
      try {
        fs.watch(ideApp, { recursive: true }, (eventType, filename) => {
          if (!filename) return;
          const lower = filename.toLowerCase();
          if (lower.includes('.bak') || lower.includes('.tmp')) return;
          if (lower.includes('jetski') || lower.includes('product.json') || lower.includes('preload.js') || lower.includes('main.css')) {
            triggerSelfHeal(`IDE resource modified: ${filename}`);
          }
        });
      } catch (err) {
        console.warn('   ⚠ Could not attach watcher to IDE resources:', err.message);
      }
    }
  }

  console.log('✓ Watcher is active and running. Press Ctrl+C to exit.\n');
}

/**
 * Installs a silent Windows background service (Task Scheduler + VBS Launcher)
 * that automatically starts the watcher on user logon without opening any console window.
 */
function installService() {
  console.log('\n⚙ Installing Antigravity Self-Healing Background Service (Windows)...');
  const cliPath = path.resolve(__dirname, '..', 'bin', 'cli.js');
  const vbsPath = path.resolve(__dirname, '..', 'antigravity-watcher-silent.vbs');
  const nodeExe = process.execPath.replace(/\\/g, '\\\\');

  // Stop any prior instances before installing
  try {
    execSync('powershell -NoProfile -Command "Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like \'*antigravity-scroll-unpin*--watch*\' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }"', { stdio: 'pipe' });
  } catch (_) {}

  const vbsContent = `' Generated by antigravity-scroll-unpin
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run """" & "${nodeExe}" & """ """ & "${cliPath.replace(/\\/g, '\\\\')}" & """ --watch", 0, False
`;

  fs.writeFileSync(vbsPath, vbsContent, 'utf8');

  // Register into Windows Task Scheduler
  try {
    const cmd = `schtasks /Create /TN "${TASK_NAME}" /TR "wscript.exe \\"${vbsPath}\\"" /SC ONLOGON /F /RL LIMITED`;
    execSync(cmd, { stdio: 'pipe' });
    console.log(`✓ Windows Scheduled Task "${TASK_NAME}" registered successfully!`);
    console.log('✓ The watcher will now run silently in the background on every Windows login.');

    // Also start it immediately
    try {
      execSync(`schtasks /Run /TN "${TASK_NAME}"`, { stdio: 'pipe' });
      console.log('✓ Service started immediately in the background.');
    } catch (_) {}

    return { success: true };
  } catch (err) {
    // Fallback: Copy VBS shortcut into Windows Startup folder
    console.warn(`⚠ Task scheduler registration failed (${err.message}). Attempting Startup folder fallback...`);
    try {
      const startupDir = path.join(process.env.APPDATA || '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
      const targetVbs = path.join(startupDir, 'AntigravityScrollUnpinWatcher.vbs');
      fs.copyFileSync(vbsPath, targetVbs);
      console.log(`✓ Placed silent startup script into: ${targetVbs}`);
      
      // Start in background
      spawn('wscript.exe', [targetVbs], { detached: true, stdio: 'ignore' }).unref();
      console.log('✓ Service started in background.');
      return { success: true };
    } catch (fallbackErr) {
      console.error('✗ Failed to install background service:', fallbackErr.message);
      return { success: false, error: fallbackErr.message };
    }
  }
}

/**
 * Uninstalls the Windows background service and stops any running watcher.
 */
function uninstallService() {
  console.log('\n🗑 Uninstalling Antigravity Self-Healing Background Service...');
  try {
    execSync(`schtasks /Delete /TN "${TASK_NAME}" /F`, { stdio: 'pipe' });
    console.log(`✓ Removed Windows Scheduled Task "${TASK_NAME}"`);
  } catch (_) {}

  try {
    const startupDir = path.join(process.env.APPDATA || '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
    const targetVbs = path.join(startupDir, 'AntigravityScrollUnpinWatcher.vbs');
    if (fs.existsSync(targetVbs)) {
      fs.unlinkSync(targetVbs);
      console.log(`✓ Removed Startup folder script: ${targetVbs}`);
    }
  } catch (_) {}

  // Stop running instances if any
  try {
    execSync('powershell -NoProfile -Command "Get-CimInstance Win32_Process | Where-Object { $_.CommandLine -like \'*antigravity-scroll-unpin*--watch*\' } | ForEach-Object { Stop-Process -Id $_.ProcessId -Force }"', { stdio: 'pipe' });
  } catch (_) {}

  console.log('✨ Background service uninstalled successfully.\n');
  return { success: true };
}

module.exports = {
  startWatcher,
  installService,
  uninstallService,
};
