const fs = require('fs');
const path = require('path');
const { execSync, spawn } = require('child_process');
const { detectPaths } = require('./detector');
const { patchIde } = require('./patcher-ide');
const { patchStandalone } = require('./patcher-standalone');
const { clearV8Cache } = require('./cache');

const TASK_NAME = 'AntigravityScrollUnpinWatcher';

/**
 * Starts continuous monitoring of Antigravity installation directories.
 * Automatically re-applies patches whenever Google Antigravity updates.
 */
function startWatcher() {
  const paths = detectPaths();
  console.log('\n======================================================');
  console.log('   Antigravity Scroll Unpin - Self-Healing Watcher');
  console.log('======================================================\n');

  if (!paths.standalone && !paths.ide) {
    console.error('✗ No Antigravity installations detected to monitor.');
    process.exit(1);
  }

  console.log('Monitoring target directories for updates:');
  if (paths.standalone) {
    console.log(`  [Standalone] ${path.join(paths.standalone, 'resources')}`);
  }
  if (paths.ide) {
    console.log(`  [IDE]        ${path.join(paths.ide, 'resources', 'app')}`);
  }

  let debounceTimer = null;
  const triggerSelfHeal = (source) => {
    if (debounceTimer) clearTimeout(debounceTimer);
    debounceTimer = setTimeout(() => {
      console.log(`\n[${new Date().toLocaleTimeString()}] ⚡ Update detected from [${source}] - Re-verifying and self-healing...`);
      try {
        if (paths.standalone) {
          const res = patchStandalone(paths.standalone);
          res.actions.forEach(a => console.log(`   ✓ ${a}`));
          res.errors.forEach(e => console.error(`   ✗ ${e}`));
        }
        if (paths.ide) {
          const res = patchIde(paths.ide);
          res.actions.forEach(a => console.log(`   ✓ ${a}`));
          res.errors.forEach(e => console.error(`   ✗ ${e}`));
        }
        if (paths.ideAppData) {
          clearV8Cache(paths.ideAppData);
        }
        console.log(`[${new Date().toLocaleTimeString()}] ✨ Self-heal completed successfully. Antigravity is protected!\n`);
      } catch (err) {
        console.error(`[${new Date().toLocaleTimeString()}] ✗ Error during self-healing:`, err.message);
      }
    }, 2000);
  };

  // Initial check & heal on start
  triggerSelfHeal('Initial Startup');

  // Watch Standalone
  if (paths.standalone) {
    const standaloneRes = path.join(paths.standalone, 'resources');
    if (fs.existsSync(standaloneRes)) {
      try {
        fs.watch(standaloneRes, { recursive: false }, (eventType, filename) => {
          if (filename && filename.toLowerCase().includes('app.asar') && !filename.includes('.bak')) {
            triggerSelfHeal('Standalone app.asar modified');
          }
        });
      } catch (err) {
        console.warn('   ⚠ Could not attach watcher to Standalone resources:', err.message);
      }
    }
  }

  // Watch IDE
  if (paths.ide) {
    const ideApp = path.join(paths.ide, 'resources', 'app');
    if (fs.existsSync(ideApp)) {
      try {
        fs.watch(ideApp, { recursive: true }, (eventType, filename) => {
          if (!filename) return;
          const lower = filename.toLowerCase();
          if (lower.includes('.bak') || lower.includes('.tmp')) return;
          if (lower.includes('jetski') || lower.includes('product.json') || lower.includes('preload.js') || lower.includes('main.css')) {
            triggerSelfHeal(`IDE resource modified: ${filename}`);
          }
        });
      } catch (err) {
        console.warn('   ⚠ Could not attach watcher to IDE resources:', err.message);
      }
    }
  }

  console.log('✓ Watcher is active and running. Press Ctrl+C to exit.\n');
}

/**
 * Installs a silent Windows background service (Task Scheduler + VBS Launcher)
 * that automatically starts the watcher on user logon without opening any console window.
 */
function installService() {
  console.log('\n⚙ Installing Antigravity Self-Healing Background Service (Windows)...');
  const cliPath = path.resolve(__dirname, '..', 'bin', 'cli.js');
  const vbsPath = path.resolve(__dirname, '..', 'antigravity-watcher-silent.vbs');

  const vbsContent = `' Generated by antigravity-scroll-unpin
Set WshShell = CreateObject("WScript.Shell")
WshShell.Run "node """ & "${cliPath.replace(/\\/g, '\\\\')}" & """ --watch", 0, False
`;

  fs.writeFileSync(vbsPath, vbsContent, 'utf8');

  // Register into Windows Task Scheduler
  try {
    const cmd = `schtasks /Create /TN "${TASK_NAME}" /TR "wscript.exe \\"${vbsPath}\\"" /SC ONLOGON /F /RL LIMITED`;
    execSync(cmd, { stdio: 'pipe' });
    console.log(`✓ Windows Scheduled Task "${TASK_NAME}" registered successfully!`);
    console.log('✓ The watcher will now run silently in the background on every Windows login.');

    // Also start it immediately
    try {
      execSync(`schtasks /Run /TN "${TASK_NAME}"`, { stdio: 'pipe' });
      console.log('✓ Service started immediately in the background.');
    } catch (_) {}

    return { success: true };
  } catch (err) {
    // Fallback: Copy VBS shortcut into Windows Startup folder
    console.warn(`⚠ Task scheduler registration failed (${err.message}). Attempting Startup folder fallback...`);
    try {
      const startupDir = path.join(process.env.APPDATA || '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
      const targetVbs = path.join(startupDir, 'AntigravityScrollUnpinWatcher.vbs');
      fs.copyFileSync(vbsPath, targetVbs);
      console.log(`✓ Placed silent startup script into: ${targetVbs}`);
      
      // Start in background
      spawn('wscript.exe', [targetVbs], { detached: true, stdio: 'ignore' }).unref();
      console.log('✓ Service started in background.');
      return { success: true };
    } catch (fallbackErr) {
      console.error('✗ Failed to install background service:', fallbackErr.message);
      return { success: false, error: fallbackErr.message };
    }
  }
}

/**
 * Uninstalls the Windows background service and stops any running watcher.
 */
function uninstallService() {
  console.log('\n🗑 Uninstalling Antigravity Self-Healing Background Service...');
  try {
    execSync(`schtasks /Delete /TN "${TASK_NAME}" /F`, { stdio: 'pipe' });
    console.log(`✓ Removed Windows Scheduled Task "${TASK_NAME}"`);
  } catch (_) {}

  try {
    const startupDir = path.join(process.env.APPDATA || '', 'Microsoft', 'Windows', 'Start Menu', 'Programs', 'Startup');
    const targetVbs = path.join(startupDir, 'AntigravityScrollUnpinWatcher.vbs');
    if (fs.existsSync(targetVbs)) {
      fs.unlinkSync(targetVbs);
      console.log(`✓ Removed Startup folder script: ${targetVbs}`);
    }
  } catch (_) {}

  // Stop running instances if any
  try {
    execSync('taskkill /F /FI "WINDOWTITLE eq AntigravityScrollUnpinWatcher*"', { stdio: 'pipe' });
  } catch (_) {}

  console.log('✨ Background service uninstalled successfully.\n');
  return { success: true };
}

module.exports = {
  startWatcher,
  installService,
  uninstallService,
};
